name: Build & Push Docker Images & Deploy Aliyun

on:
    push:
      branches:
        - release/*
    release:
      types: [published]

jobs:
  confirm-ecs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: SSH to ECS and check/install Docker
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ECS_SSH_PRIVATE_KEY }}
          ECS_IP: ${{ secrets.ECS_IP }}
          ECS_USER: ${{ secrets.ECS_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem $ECS_USER@$ECS_IP << EOF
              # 检查 Docker 是否已安装
              if ! command -v docker &> /dev/null; then
                  echo "Docker 未安装，正在安装..."
                  # 安装 Docker 的命令
                  sudo yum update -y
                  sudo yum install -y yum-utils device-mapper-persistent-data lvm2
                  sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
                  sudo yum install -y docker-ce docker-ce-cli containerd.io
                  sudo systemctl start docker
                  sudo systemctl enable docker
                  echo "Docker 安装完成."
              else
                  echo "Docker 已安装，版本为：$(docker --version)"
              fi
          EOF
  build-and-push:
    needs: [confirm-ecs]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [backend, app]
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
            
        
