name: Build & Push Docker Images & Deploy Aliyun

on:
  push:
    branches:
      - release/*

jobs:
  check-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            fetch-depth: 5
      - name: Get changed files
        id: get_changed_files
        run: |
          # 获取上一个提交的SHA
          PREVIOUS_COMMIT=$(git rev-parse HEAD^)
          
          # 获取变更文件，并筛选出特定目录（例如：src/）
          CHANGED_FILES=$(git diff --name-only $PREVIOUS_COMMIT HEAD -- src/)
          
          # 将变更文件输出为环境变量
          echo "changed_files=$CHANGED_FILES" >> $GITHUB_ENV
          echo "src changed_files=$CHANGED_FILES"

          # 获取变更文件，并筛选出特定目录（例如：./）
          CHANGED_FILES=$(git diff --name-only $PREVIOUS_COMMIT HEAD -- ./)
          
          # 将变更文件输出为环境变量
          echo "changed_files=$CHANGED_FILES" >> $GITHUB_ENV
          echo ". changed_files=$CHANGED_FILES"

      - name: Output changed files
        run: |
          echo "Changed files in 'src/' directory:"
          echo "${{ env.changed_files }}"

